version: 2

builds:
  binary: runlike
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - windows
  goarch:
    - amd64
    - arm64

dockers:
  - image_templates:
      #- "turtletowerz/runlike-go:{{ .Tag }}"
      - "ghcr.io/turtletowerz/runlike-go:{{ .Tag }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"
