name: build-release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for goreleaser. See: https://goreleaser.com/ci/actions#workflow
      
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      # TODO: Implement binary signing
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
